<LogoScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.get_bg()
    AnchorLayout:
        anchor_y: 'bottom'
        padding: [0, 0, 0, 50]

        Button:
            text: "Start"
            font_size: '15sp'
            size_hint: (None, None)
            on_press: root.manager.current = 'file_chooser'
            size: 100, 50

<FileChooserScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.get_bg()

    AnchorLayout:
        anchor_y: 'bottom'
        padding: [0, 0, 0, 50]

        PathButton:
            text: 'Load archive'
            font_size: '15sp'
            size_hint: (None, None)
            on_press: self.get_path()
            size: 100, 50

<AttackMethodScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.get_bg()

    AnchorLayout:
        anchor_y: 'bottom'
        anchor_x: 'center'
        padding: [0, 0, 0, 10]

        BoxLayout:
            size_hint: None, None
            orientation: "vertical"

            Button:
                text: 'Dictionary'
                font_size: '15sp'
                size_hint: (None, None)
                on_press: root.manager.current = 'crack'
                on_release: root.dictionary_attack()
                size: 100, 50

            Button:
                text: 'Brute Force'
                font_size: '15sp'
                size_hint: (None, None)
                on_press: root.manager.current = 'crack'
                on_release: root.brute_force_attack()
                size: 100, 50

<CrackScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.get_bg()

    AnchorLayout:
        anchor_y: 'bottom'
        anchor_x: 'center'
        padding: [0, 0, 0, 0]

        BoxLayout:
            size_hint: None, None
            orientation: "vertical"

            spacing: 0
            padding: 1

            Label:
                text: 'Searching for password... Please wait ... '
                color: 0.15, 0.09, 0.00, 1
                font_size: '20sp'
                bold: True

            Label:
                text: 'It can take between a few seconds and a few days...'
                color: 0.15, 0.09, 0.00, 1
                font_size: '16sp'
                bold: True

<ResultCompletedScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.get_bg()

    AnchorLayout:
        anchor_y: 'bottom'
        anchor_x: 'center'
        padding: [0, 0, 0, 20]

        BoxLayout:
            size_hint: None, None
            orientation: "vertical"

            spacing: 0
            padding: 1

            Label:
                id: label
                text: 'pass'
                color: 0.15, 0.09, 0.00, 1
                font_size: '15sp'
                bold: True

            CopyButton:
                text: 'Copy to clipboard'
                on_press: self.copy()
                font_size: '10sp'


<ResultFailedScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.get_bg()

    AnchorLayout:
        anchor_y: 'bottom'
        anchor_x: 'center'
        padding: [0, 0, 0, 20]

        BoxLayout:
            size_hint: None, None
            orientation: "horizontal"

            spacing: 10

            Button:
                text: 'Try again'
                on_press: root.manager.current = 'attack_method'
                size_hint: .5, None
                size: 100, 30
                font_size: '10sp'

            Button:
                text: 'Exit'
                on_press: root.manager.current = ''
                size_hint: .5, None
                size: 100, 30
                font_size: '10sp'